// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: p2p_stream.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ------------------------------------------------------------
// ResponseType
// ------------------------------------------------------------
// Defines the type of response returned by the node.
type ResponseType int32

const (
	ResponseType_Unknown               ResponseType = 0 // Unspecified / invalid type
	ResponseType_Message               ResponseType = 1 // Standard message payload
	ResponseType_MessageTraceMumP2P    ResponseType = 2 // Tracing/debug info from mumP2P
	ResponseType_MessageTraceGossipSub ResponseType = 3 // Tracing/debug info from GossipSub
)

// Enum value maps for ResponseType.
var (
	ResponseType_name = map[int32]string{
		0: "Unknown",
		1: "Message",
		2: "MessageTraceMumP2P",
		3: "MessageTraceGossipSub",
	}
	ResponseType_value = map[string]int32{
		"Unknown":               0,
		"Message":               1,
		"MessageTraceMumP2P":    2,
		"MessageTraceGossipSub": 3,
	}
)

func (x ResponseType) Enum() *ResponseType {
	p := new(ResponseType)
	*p = x
	return p
}

func (x ResponseType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResponseType) Descriptor() protoreflect.EnumDescriptor {
	return file_p2p_stream_proto_enumTypes[0].Descriptor()
}

func (ResponseType) Type() protoreflect.EnumType {
	return &file_p2p_stream_proto_enumTypes[0]
}

func (x ResponseType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResponseType.Descriptor instead.
func (ResponseType) EnumDescriptor() ([]byte, []int) {
	return file_p2p_stream_proto_rawDescGZIP(), []int{0}
}

// Empty message for requests that don't require input.
type Void struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Void) Reset() {
	*x = Void{}
	mi := &file_p2p_stream_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Void) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Void) ProtoMessage() {}

func (x *Void) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_stream_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Void.ProtoReflect.Descriptor instead.
func (*Void) Descriptor() ([]byte, []int) {
	return file_p2p_stream_proto_rawDescGZIP(), []int{0}
}

// ------------------------------------------------------------
// HealthResponse
// ------------------------------------------------------------
// Provides health and resource usage information about a node.
type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`                          // true = node is healthy, false = unhealthy
	NodeMode      string                 `protobuf:"bytes,2,opt,name=nodeMode,proto3" json:"nodeMode,omitempty"`                       // operating mode (e.g., "gateway", "relay", "hybrid")
	MemoryUsed    float32                `protobuf:"fixed32,3,opt,name=memoryUsed,proto3" json:"memoryUsed,omitempty"`                 // memory usage (%)
	CpuUsed       float32                `protobuf:"fixed32,4,opt,name=cpuUsed,proto3" json:"cpuUsed,omitempty"`                       // CPU usage (%)
	DiskUsed      float32                `protobuf:"fixed32,5,opt,name=diskUsed,proto3" json:"diskUsed,omitempty"`                     // disk usage (%)
	P2PAddress    string                 `protobuf:"bytes,6,opt,name=p2pAddress,proto3" json:"p2pAddress,omitempty"`                   // libp2p or mumP2P multiaddress of the node
	Country       string                 `protobuf:"bytes,7,opt,name=country,proto3" json:"country,omitempty"`                         // country name of the node
	CountryIso    string                 `protobuf:"bytes,8,opt,name=country_iso,json=countryIso,proto3" json:"country_iso,omitempty"` // country ISO code of the node
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_p2p_stream_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_stream_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_p2p_stream_proto_rawDescGZIP(), []int{1}
}

func (x *HealthResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *HealthResponse) GetNodeMode() string {
	if x != nil {
		return x.NodeMode
	}
	return ""
}

func (x *HealthResponse) GetMemoryUsed() float32 {
	if x != nil {
		return x.MemoryUsed
	}
	return 0
}

func (x *HealthResponse) GetCpuUsed() float32 {
	if x != nil {
		return x.CpuUsed
	}
	return 0
}

func (x *HealthResponse) GetDiskUsed() float32 {
	if x != nil {
		return x.DiskUsed
	}
	return 0
}

func (x *HealthResponse) GetP2PAddress() string {
	if x != nil {
		return x.P2PAddress
	}
	return ""
}

func (x *HealthResponse) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *HealthResponse) GetCountryIso() string {
	if x != nil {
		return x.CountryIso
	}
	return ""
}

// ------------------------------------------------------------
// Request
// ------------------------------------------------------------
// A command sent from the Optimum Proxy to the node.
type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       int32                  `protobuf:"varint,1,opt,name=command,proto3" json:"command,omitempty"`                  // Numeric command identifier (protocol-defined)
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`                         // Command payload (serialized object or raw bytes)
	Topic         string                 `protobuf:"bytes,3,opt,name=topic,proto3" json:"topic,omitempty"`                       // Target topic (if applicable)
	JwtToken      string                 `protobuf:"bytes,4,opt,name=jwt_token,json=jwtToken,proto3" json:"jwt_token,omitempty"` // Auth token for validation & rate limiting
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_p2p_stream_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_stream_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_p2p_stream_proto_rawDescGZIP(), []int{2}
}

func (x *Request) GetCommand() int32 {
	if x != nil {
		return x.Command
	}
	return 0
}

func (x *Request) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Request) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *Request) GetJwtToken() string {
	if x != nil {
		return x.JwtToken
	}
	return ""
}

// ------------------------------------------------------------
// Response
// ------------------------------------------------------------
// A response sent from the node back to the Optimum Proxy.
type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       ResponseType           `protobuf:"varint,1,opt,name=command,proto3,enum=proto.ResponseType" json:"command,omitempty"` // Type of response (see ResponseType enum)
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`                                // Response payload
	Metadata      []byte                 `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`                        // Extra metadata (optional: headers, trace, proofs)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_p2p_stream_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_stream_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_p2p_stream_proto_rawDescGZIP(), []int{3}
}

func (x *Response) GetCommand() ResponseType {
	if x != nil {
		return x.Command
	}
	return ResponseType_Unknown
}

func (x *Response) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Response) GetMetadata() []byte {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// ------------------------------------------------------------
// TopicList
// ------------------------------------------------------------
// Represents the list of active topics subscribed to by a node.
type TopicList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topics        []string               `protobuf:"bytes,1,rep,name=topics,proto3" json:"topics,omitempty"` // Array of topic strings
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopicList) Reset() {
	*x = TopicList{}
	mi := &file_p2p_stream_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopicList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopicList) ProtoMessage() {}

func (x *TopicList) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_stream_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopicList.ProtoReflect.Descriptor instead.
func (*TopicList) Descriptor() ([]byte, []int) {
	return file_p2p_stream_proto_rawDescGZIP(), []int{4}
}

func (x *TopicList) GetTopics() []string {
	if x != nil {
		return x.Topics
	}
	return nil
}

var File_p2p_stream_proto protoreflect.FileDescriptor

const file_p2p_stream_proto_rawDesc = "" +
	"\n" +
	"\x10p2p_stream.proto\x12\x05proto\"\x06\n" +
	"\x04Void\"\xf5\x01\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\bR\x06status\x12\x1a\n" +
	"\bnodeMode\x18\x02 \x01(\tR\bnodeMode\x12\x1e\n" +
	"\n" +
	"memoryUsed\x18\x03 \x01(\x02R\n" +
	"memoryUsed\x12\x18\n" +
	"\acpuUsed\x18\x04 \x01(\x02R\acpuUsed\x12\x1a\n" +
	"\bdiskUsed\x18\x05 \x01(\x02R\bdiskUsed\x12\x1e\n" +
	"\n" +
	"p2pAddress\x18\x06 \x01(\tR\n" +
	"p2pAddress\x12\x18\n" +
	"\acountry\x18\a \x01(\tR\acountry\x12\x1f\n" +
	"\vcountry_iso\x18\b \x01(\tR\n" +
	"countryIso\"j\n" +
	"\aRequest\x12\x18\n" +
	"\acommand\x18\x01 \x01(\x05R\acommand\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x14\n" +
	"\x05topic\x18\x03 \x01(\tR\x05topic\x12\x1b\n" +
	"\tjwt_token\x18\x04 \x01(\tR\bjwtToken\"i\n" +
	"\bResponse\x12-\n" +
	"\acommand\x18\x01 \x01(\x0e2\x13.proto.ResponseTypeR\acommand\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x1a\n" +
	"\bmetadata\x18\x03 \x01(\fR\bmetadata\"#\n" +
	"\tTopicList\x12\x16\n" +
	"\x06topics\x18\x01 \x03(\tR\x06topics*[\n" +
	"\fResponseType\x12\v\n" +
	"\aUnknown\x10\x00\x12\v\n" +
	"\aMessage\x10\x01\x12\x16\n" +
	"\x12MessageTraceMumP2P\x10\x02\x12\x19\n" +
	"\x15MessageTraceGossipSub\x10\x032\xa7\x01\n" +
	"\rCommandStream\x127\n" +
	"\x0eListenCommands\x12\x0e.proto.Request\x1a\x0f.proto.Response\"\x00(\x010\x01\x12.\n" +
	"\x06Health\x12\v.proto.Void\x1a\x15.proto.HealthResponse\"\x00\x12-\n" +
	"\n" +
	"ListTopics\x12\v.proto.Void\x1a\x10.proto.TopicList\"\x00B\x06Z\x04./pbb\x06proto3"

var (
	file_p2p_stream_proto_rawDescOnce sync.Once
	file_p2p_stream_proto_rawDescData []byte
)

func file_p2p_stream_proto_rawDescGZIP() []byte {
	file_p2p_stream_proto_rawDescOnce.Do(func() {
		file_p2p_stream_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_p2p_stream_proto_rawDesc), len(file_p2p_stream_proto_rawDesc)))
	})
	return file_p2p_stream_proto_rawDescData
}

var file_p2p_stream_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_p2p_stream_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_p2p_stream_proto_goTypes = []any{
	(ResponseType)(0),      // 0: proto.ResponseType
	(*Void)(nil),           // 1: proto.Void
	(*HealthResponse)(nil), // 2: proto.HealthResponse
	(*Request)(nil),        // 3: proto.Request
	(*Response)(nil),       // 4: proto.Response
	(*TopicList)(nil),      // 5: proto.TopicList
}
var file_p2p_stream_proto_depIdxs = []int32{
	0, // 0: proto.Response.command:type_name -> proto.ResponseType
	3, // 1: proto.CommandStream.ListenCommands:input_type -> proto.Request
	1, // 2: proto.CommandStream.Health:input_type -> proto.Void
	1, // 3: proto.CommandStream.ListTopics:input_type -> proto.Void
	4, // 4: proto.CommandStream.ListenCommands:output_type -> proto.Response
	2, // 5: proto.CommandStream.Health:output_type -> proto.HealthResponse
	5, // 6: proto.CommandStream.ListTopics:output_type -> proto.TopicList
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_p2p_stream_proto_init() }
func file_p2p_stream_proto_init() {
	if File_p2p_stream_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_p2p_stream_proto_rawDesc), len(file_p2p_stream_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_p2p_stream_proto_goTypes,
		DependencyIndexes: file_p2p_stream_proto_depIdxs,
		EnumInfos:         file_p2p_stream_proto_enumTypes,
		MessageInfos:      file_p2p_stream_proto_msgTypes,
	}.Build()
	File_p2p_stream_proto = out.File
	file_p2p_stream_proto_goTypes = nil
	file_p2p_stream_proto_depIdxs = nil
}
