// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: telemetry.proto

package telemetry

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Blocknumber   int64                  `protobuf:"varint,1,opt,name=blocknumber,proto3" json:"blocknumber,omitempty"`
	Slot          int64                  `protobuf:"varint,2,opt,name=slot,proto3" json:"slot,omitempty"`          // Your ~400 bytes of text
	Blockhash     string                 `protobuf:"bytes,3,opt,name=blockhash,proto3" json:"blockhash,omitempty"` // Your ~400 bytes of text
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Blocksize     int64                  `protobuf:"varint,5,opt,name=blocksize,proto3" json:"blocksize,omitempty"`
	ClientName    string                 `protobuf:"bytes,6,opt,name=client_name,json=clientName,proto3" json:"client_name,omitempty"`
	Type          string                 `protobuf:"bytes,7,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_telemetry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_telemetry_proto_rawDescGZIP(), []int{0}
}

func (x *LogEntry) GetBlocknumber() int64 {
	if x != nil {
		return x.Blocknumber
	}
	return 0
}

func (x *LogEntry) GetSlot() int64 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *LogEntry) GetBlockhash() string {
	if x != nil {
		return x.Blockhash
	}
	return ""
}

func (x *LogEntry) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *LogEntry) GetBlocksize() int64 {
	if x != nil {
		return x.Blocksize
	}
	return 0
}

func (x *LogEntry) GetClientName() string {
	if x != nil {
		return x.ClientName
	}
	return ""
}

func (x *LogEntry) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type UploadSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	CountReceived int32                  `protobuf:"varint,2,opt,name=count_received,json=countReceived,proto3" json:"count_received,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadSummary) Reset() {
	*x = UploadSummary{}
	mi := &file_telemetry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadSummary) ProtoMessage() {}

func (x *UploadSummary) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadSummary.ProtoReflect.Descriptor instead.
func (*UploadSummary) Descriptor() ([]byte, []int) {
	return file_telemetry_proto_rawDescGZIP(), []int{1}
}

func (x *UploadSummary) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UploadSummary) GetCountReceived() int32 {
	if x != nil {
		return x.CountReceived
	}
	return 0
}

var File_telemetry_proto protoreflect.FileDescriptor

const file_telemetry_proto_rawDesc = "" +
	"\n" +
	"\x0ftelemetry.proto\x12\ttelemetry\"\xcf\x01\n" +
	"\bLogEntry\x12 \n" +
	"\vblocknumber\x18\x01 \x01(\x03R\vblocknumber\x12\x12\n" +
	"\x04slot\x18\x02 \x01(\x03R\x04slot\x12\x1c\n" +
	"\tblockhash\x18\x03 \x01(\tR\tblockhash\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x12\x1c\n" +
	"\tblocksize\x18\x05 \x01(\x03R\tblocksize\x12\x1f\n" +
	"\vclient_name\x18\x06 \x01(\tR\n" +
	"clientName\x12\x12\n" +
	"\x04type\x18\a \x01(\tR\x04type\"N\n" +
	"\rUploadSummary\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12%\n" +
	"\x0ecount_received\x18\x02 \x01(\x05R\rcountReceived2O\n" +
	"\x10TelemetryService\x12;\n" +
	"\bSendLogs\x12\x13.telemetry.LogEntry\x1a\x18.telemetry.UploadSummary(\x01B\rZ\v./telemetryb\x06proto3"

var (
	file_telemetry_proto_rawDescOnce sync.Once
	file_telemetry_proto_rawDescData []byte
)

func file_telemetry_proto_rawDescGZIP() []byte {
	file_telemetry_proto_rawDescOnce.Do(func() {
		file_telemetry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_telemetry_proto_rawDesc), len(file_telemetry_proto_rawDesc)))
	})
	return file_telemetry_proto_rawDescData
}

var file_telemetry_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_telemetry_proto_goTypes = []any{
	(*LogEntry)(nil),      // 0: telemetry.LogEntry
	(*UploadSummary)(nil), // 1: telemetry.UploadSummary
}
var file_telemetry_proto_depIdxs = []int32{
	0, // 0: telemetry.TelemetryService.SendLogs:input_type -> telemetry.LogEntry
	1, // 1: telemetry.TelemetryService.SendLogs:output_type -> telemetry.UploadSummary
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_telemetry_proto_init() }
func file_telemetry_proto_init() {
	if File_telemetry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_telemetry_proto_rawDesc), len(file_telemetry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_telemetry_proto_goTypes,
		DependencyIndexes: file_telemetry_proto_depIdxs,
		MessageInfos:      file_telemetry_proto_msgTypes,
	}.Build()
	File_telemetry_proto = out.File
	file_telemetry_proto_goTypes = nil
	file_telemetry_proto_depIdxs = nil
}
